import { View, Text } from '@react-pdf/renderer';
import { COLORS } from '@/lib/pdf/colors';
import { styles } from '@/lib/pdf/styles';

export function ReportFooter() {
  return (
    <View style={styles.footer} fixed>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
        <Text style={styles.footerText}>
          Generated by Peak360 Longevity Program
        </Text>
        <Text
          style={styles.footerText}
          render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
        />
      </View>
      <Text style={{ fontSize: 6, color: COLORS.textFaint, marginTop: 2 }}>
        This report is for informational purposes only and does not constitute medical advice. Always consult with a qualified healthcare professional before making changes to your health regimen.
      </Text>
    </View>
  );
}
