import type { NormativeData } from '@/types/normative';

export const normativeData: NormativeData = {
  blood_tests: {
    cholesterol_total: {
      unit: 'mmol/L',
      note: 'Targets for general adult population (not individualized medical advice).',
      poor: { min: 6.2, max: 99 },
      cautious: { min: 5.2, max: 6.19 },
      normal: { min: 4.0, max: 5.19 },
      great: { min: 3.5, max: 3.99 },
      elite: { min: 0.0, max: 3.49 },
    },
    ldl_cholesterol: {
      unit: 'mmol/L',
      poor: { min: 4.1, max: 99 },
      cautious: { min: 3.4, max: 4.09 },
      normal: { min: 2.6, max: 3.39 },
      great: { min: 1.8, max: 2.59 },
      elite: { min: 0.0, max: 1.79 },
    },
    hdl_cholesterol: {
      unit: 'mmol/L',
      note: 'Higher is generally better.',
      poor: { min: 0.0, max: 0.99 },
      cautious: { min: 1.0, max: 1.19 },
      normal: { min: 1.2, max: 1.49 },
      great: { min: 1.5, max: 1.79 },
      elite: { min: 1.8, max: 99 },
    },
    triglycerides: {
      unit: 'mmol/L',
      poor: { min: 2.3, max: 99 },
      cautious: { min: 1.7, max: 2.29 },
      normal: { min: 1.0, max: 1.69 },
      great: { min: 0.7, max: 0.99 },
      elite: { min: 0.0, max: 0.69 },
    },
    fasting_glucose: {
      unit: 'mmol/L',
      poor: { min: 7.0, max: 99 },
      cautious: { min: 5.6, max: 6.99 },
      normal: { min: 4.0, max: 5.59 },
      great: { min: 3.7, max: 3.99 },
      elite: { min: 0.0, max: 3.69 },
    },
    hba1c: {
      unit: '%',
      poor: { min: 6.5, max: 99 },
      cautious: { min: 5.7, max: 6.49 },
      normal: { min: 5.0, max: 5.69 },
      great: { min: 4.7, max: 4.99 },
      elite: { min: 0.0, max: 4.69 },
    },
    crp_hs: {
      unit: 'mg/L',
      note: 'Lower is generally better (systemic inflammation marker).',
      poor: { min: 3.0, max: 99 },
      cautious: { min: 1.1, max: 2.99 },
      normal: { min: 0.6, max: 1.09 },
      great: { min: 0.3, max: 0.59 },
      elite: { min: 0.0, max: 0.29 },
    },
    vitamin_d_25oh: {
      unit: 'nmol/L',
      note: 'Reference targets vary by lab and context.',
      poor: { min: 0.0, max: 49 },
      cautious: { min: 50, max: 74 },
      normal: { min: 75, max: 124 },
      great: { min: 125, max: 149 },
      elite: { min: 150, max: 300 },
    },
    hemoglobin: {
      unit: 'g/dL',
      note: 'Oxygen-carrying capacity; lower in females is physiologically normal.',
      male: {
        poor: { min: 0, max: 12.9 },
        cautious: { min: 13.0, max: 13.9 },
        normal: { min: 14.0, max: 16.9 },
        great: { min: 17.0, max: 17.9 },
        elite: { min: 18.0, max: 22 },
      },
      female: {
        poor: { min: 0, max: 10.9 },
        cautious: { min: 11.0, max: 11.9 },
        normal: { min: 12.0, max: 15.4 },
        great: { min: 15.5, max: 16.4 },
        elite: { min: 16.5, max: 22 },
      },
    },
    hematocrit: {
      unit: '%',
      note: 'Percentage of blood volume occupied by red blood cells.',
      male: {
        poor: { min: 0, max: 37.9 },
        cautious: { min: 38.0, max: 39.9 },
        normal: { min: 40.0, max: 54.0 },
        great: { min: 54.1, max: 56.0 },
        elite: { min: 56.1, max: 65 },
      },
      female: {
        poor: { min: 0, max: 33.9 },
        cautious: { min: 34.0, max: 35.9 },
        normal: { min: 36.0, max: 48.0 },
        great: { min: 48.1, max: 50.0 },
        elite: { min: 50.1, max: 65 },
      },
    },
    rbc: {
      unit: 'M/mcL',
      note: 'Red blood cell count; higher in males due to testosterone and erythropoietin.',
      male: {
        poor: { min: 0, max: 4.09 },
        cautious: { min: 4.1, max: 4.69 },
        normal: { min: 4.7, max: 6.1 },
        great: { min: 6.11, max: 6.5 },
        elite: { min: 6.51, max: 8 },
      },
      female: {
        poor: { min: 0, max: 3.69 },
        cautious: { min: 3.7, max: 4.19 },
        normal: { min: 4.2, max: 5.4 },
        great: { min: 5.41, max: 5.8 },
        elite: { min: 5.81, max: 8 },
      },
    },
    ferritin: {
      unit: 'ng/mL',
      note: 'Iron storage protein; lower in premenopausal females is common.',
      male: {
        poor: { min: 0, max: 11.9 },
        cautious: { min: 12.0, max: 29.9 },
        normal: { min: 30.0, max: 300.0 },
        great: { min: 300.1, max: 400.0 },
        elite: { min: 400.1, max: 600 },
      },
      female: {
        poor: { min: 0, max: 9.9 },
        cautious: { min: 10.0, max: 19.9 },
        normal: { min: 20.0, max: 150.0 },
        great: { min: 150.1, max: 200.0 },
        elite: { min: 200.1, max: 400 },
      },
    },
    serum_iron: {
      unit: 'ug/dL',
      note: 'Circulating iron; varies with dietary intake and menstrual status.',
      male: {
        poor: { min: 0, max: 44.9 },
        cautious: { min: 45.0, max: 54.9 },
        normal: { min: 55.0, max: 160.0 },
        great: { min: 160.1, max: 180.0 },
        elite: { min: 180.1, max: 250 },
      },
      female: {
        poor: { min: 0, max: 29.9 },
        cautious: { min: 30.0, max: 39.9 },
        normal: { min: 40.0, max: 155.0 },
        great: { min: 155.1, max: 175.0 },
        elite: { min: 175.1, max: 250 },
      },
    },
    total_testosterone: {
      unit: 'ng/dL',
      note: 'Primary androgen; dramatically different ranges between sexes.',
      male: {
        poor: { min: 0, max: 249 },
        cautious: { min: 250, max: 299 },
        normal: { min: 300, max: 1000 },
        great: { min: 1001, max: 1200 },
        elite: { min: 1201, max: 1500 },
      },
      female: {
        poor: { min: 0, max: 7.9 },
        cautious: { min: 8.0, max: 14.9 },
        normal: { min: 15.0, max: 70.0 },
        great: { min: 70.1, max: 85.0 },
        elite: { min: 85.1, max: 120 },
      },
    },
    free_testosterone: {
      unit: 'pg/mL',
      note: 'Bioavailable testosterone fraction; most clinically relevant for symptoms.',
      male: {
        poor: { min: 0, max: 4.4 },
        cautious: { min: 4.5, max: 4.9 },
        normal: { min: 5.0, max: 21.0 },
        great: { min: 21.1, max: 25.0 },
        elite: { min: 25.1, max: 35 },
      },
      female: {
        poor: { min: 0, max: 0.14 },
        cautious: { min: 0.15, max: 0.29 },
        normal: { min: 0.3, max: 1.9 },
        great: { min: 1.91, max: 2.5 },
        elite: { min: 2.51, max: 4 },
      },
    },
    creatinine: {
      unit: 'mg/dL',
      note: 'Kidney filtration byproduct; higher in males due to greater muscle mass.',
      male: {
        poor: { min: 1.4, max: 15 },
        cautious: { min: 1.31, max: 1.39 },
        normal: { min: 0.7, max: 1.3 },
        great: { min: 0.6, max: 0.69 },
        elite: { min: 0, max: 0.59 },
      },
      female: {
        poor: { min: 1.2, max: 15 },
        cautious: { min: 1.11, max: 1.19 },
        normal: { min: 0.6, max: 1.1 },
        great: { min: 0.5, max: 0.59 },
        elite: { min: 0, max: 0.49 },
      },
    },
    egfr: {
      unit: 'mL/min',
      note: 'Estimated glomerular filtration rate; higher is better. Calculated differently by sex in clinical practice.',
      male: {
        poor: { min: 0, max: 29.9 },
        cautious: { min: 30.0, max: 59.9 },
        normal: { min: 60.0, max: 89.9 },
        great: { min: 90.0, max: 119.9 },
        elite: { min: 120.0, max: 200 },
      },
      female: {
        poor: { min: 0, max: 29.9 },
        cautious: { min: 30.0, max: 59.9 },
        normal: { min: 60.0, max: 89.9 },
        great: { min: 90.0, max: 119.9 },
        elite: { min: 120.0, max: 200 },
      },
    },
    uric_acid: {
      unit: 'mg/dL',
      note: 'Purine metabolism byproduct; elevated levels associated with gout risk.',
      male: {
        poor: { min: 8.6, max: 20 },
        cautious: { min: 7.1, max: 8.5 },
        normal: { min: 4.0, max: 7.0 },
        great: { min: 3.0, max: 3.99 },
        elite: { min: 0, max: 2.99 },
      },
      female: {
        poor: { min: 7.4, max: 20 },
        cautious: { min: 6.1, max: 7.3 },
        normal: { min: 2.7, max: 6.0 },
        great: { min: 2.0, max: 2.69 },
        elite: { min: 0, max: 1.99 },
      },
    },
    alt: {
      unit: 'U/L',
      note: 'Liver enzyme; lower is generally better. Elevated may indicate hepatocellular damage.',
      male: {
        poor: { min: 57, max: 500 },
        cautious: { min: 41, max: 56 },
        normal: { min: 7, max: 40 },
        great: { min: 5, max: 6.99 },
        elite: { min: 0, max: 4.99 },
      },
      female: {
        poor: { min: 46, max: 500 },
        cautious: { min: 33, max: 45 },
        normal: { min: 7, max: 32 },
        great: { min: 5, max: 6.99 },
        elite: { min: 0, max: 4.99 },
      },
    },
    ast: {
      unit: 'U/L',
      note: 'Liver/muscle enzyme; lower is generally better. Can be elevated post-exercise.',
      male: {
        poor: { min: 41, max: 500 },
        cautious: { min: 34, max: 40 },
        normal: { min: 10, max: 33 },
        great: { min: 7, max: 9.99 },
        elite: { min: 0, max: 6.99 },
      },
      female: {
        poor: { min: 33, max: 500 },
        cautious: { min: 26, max: 32 },
        normal: { min: 9, max: 25 },
        great: { min: 6, max: 8.99 },
        elite: { min: 0, max: 5.99 },
      },
    },
    ggt: {
      unit: 'U/L',
      note: 'Liver enzyme sensitive to alcohol and bile duct issues; lower is better.',
      male: {
        poor: { min: 51, max: 500 },
        cautious: { min: 36, max: 50 },
        normal: { min: 0, max: 35 },
        great: { min: 0, max: 20 },
        elite: { min: 0, max: 10 },
      },
      female: {
        poor: { min: 31, max: 500 },
        cautious: { min: 21, max: 30 },
        normal: { min: 0, max: 20 },
        great: { min: 0, max: 12 },
        elite: { min: 0, max: 6 },
      },
    },
    oestradiol: {
      unit: 'pg/mL',
      note: 'Primary estrogen. Female ranges shown for follicular phase; results may vary by cycle phase.',
      male: {
        poor: { min: 0, max: 4.9 },
        cautious: { min: 5.0, max: 9.9 },
        normal: { min: 10.0, max: 40.0 },
        great: { min: 40.1, max: 50.0 },
        elite: { min: 50.1, max: 70 },
      },
      female: {
        poor: { min: 0, max: 14.9 },
        cautious: { min: 15.0, max: 29.9 },
        normal: { min: 30.0, max: 350.0 },
        great: { min: 350.1, max: 450.0 },
        elite: { min: 450.1, max: 600 },
      },
    },
    shbg: {
      unit: 'nmol/L',
      note: 'Sex hormone-binding globulin; binds and regulates bioavailable hormones.',
      male: {
        poor: { min: 0, max: 9.9 },
        cautious: { min: 10.0, max: 14.9 },
        normal: { min: 15.0, max: 57.0 },
        great: { min: 57.1, max: 70.0 },
        elite: { min: 70.1, max: 100 },
      },
      female: {
        poor: { min: 0, max: 17.9 },
        cautious: { min: 18.0, max: 24.9 },
        normal: { min: 25.0, max: 144.0 },
        great: { min: 144.1, max: 170.0 },
        elite: { min: 170.1, max: 250 },
      },
    },
    dheas: {
      unit: 'ug/dL',
      note: 'Adrenal androgen precursor; declines with age. Marker of adrenal function.',
      male: {
        poor: { min: 0, max: 179 },
        cautious: { min: 180, max: 279 },
        normal: { min: 280, max: 640 },
        great: { min: 641, max: 750 },
        elite: { min: 751, max: 1000 },
      },
      female: {
        poor: { min: 0, max: 44 },
        cautious: { min: 45, max: 64 },
        normal: { min: 65, max: 380 },
        great: { min: 381, max: 450 },
        elite: { min: 451, max: 600 },
      },
    },
    fsh: {
      unit: 'mIU/mL',
      note: 'Follicle-stimulating hormone. Female ranges shown for follicular phase; results may vary by cycle phase.',
      male: {
        poor: { min: 0, max: 0.9 },
        cautious: { min: 1.0, max: 1.4 },
        normal: { min: 1.5, max: 12.4 },
        great: { min: 12.5, max: 15.0 },
        elite: { min: 15.1, max: 20 },
      },
      female: {
        poor: { min: 0, max: 1.9 },
        cautious: { min: 2.0, max: 3.4 },
        normal: { min: 3.5, max: 12.5 },
        great: { min: 12.6, max: 15.0 },
        elite: { min: 15.1, max: 25 },
      },
    },
    lh: {
      unit: 'mIU/mL',
      note: 'Luteinizing hormone. Female ranges shown for follicular phase; results may vary by cycle phase.',
      male: {
        poor: { min: 0, max: 1.0 },
        cautious: { min: 1.1, max: 1.7 },
        normal: { min: 1.8, max: 8.6 },
        great: { min: 8.7, max: 10.0 },
        elite: { min: 10.1, max: 15 },
      },
      female: {
        poor: { min: 0, max: 1.3 },
        cautious: { min: 1.4, max: 2.3 },
        normal: { min: 2.4, max: 12.6 },
        great: { min: 12.7, max: 15.0 },
        elite: { min: 15.1, max: 20 },
      },
    },
  },

  body_comp: {
    bmi: {
      unit: 'kg/m\u00B2',
      note: 'BMI is a blunt tool; interpret with body fat, waist, and context.',
      poor: { min: 35.0, max: 99 },
      cautious: { min: 30.0, max: 34.99 },
      normal: { min: 18.5, max: 29.99 },
      great: { min: 20.0, max: 24.99 },
      elite: { min: 21.0, max: 23.99 },
    },

    bwi: {
      unit: '/10',
      note: 'Evolt 360 Bio Wellness Index — a composite body composition score.',
      poor: { min: 0, max: 3.99 },
      cautious: { min: 4.0, max: 5.99 },
      normal: { min: 6.0, max: 7.49 },
      great: { min: 7.5, max: 8.49 },
      elite: { min: 8.5, max: 10 },
    },

    body_fat_percent: {
      unit: '%',
      note: 'Age + sex bucketed. Lower isn\'t always better; interpret with health/performance goals.',
      male: {
        '20-39': {
          poor: { min: 25, max: 99 },
          cautious: { min: 20, max: 24.99 },
          normal: { min: 14, max: 19.99 },
          great: { min: 10, max: 13.99 },
          elite: { min: 0, max: 9.99 },
        },
        '40-59': {
          poor: { min: 28, max: 99 },
          cautious: { min: 23, max: 27.99 },
          normal: { min: 16, max: 22.99 },
          great: { min: 12, max: 15.99 },
          elite: { min: 0, max: 11.99 },
        },
        '60+': {
          poor: { min: 30, max: 99 },
          cautious: { min: 25, max: 29.99 },
          normal: { min: 18, max: 24.99 },
          great: { min: 14, max: 17.99 },
          elite: { min: 0, max: 13.99 },
        },
      },
      female: {
        '20-39': {
          poor: { min: 35, max: 99 },
          cautious: { min: 30, max: 34.99 },
          normal: { min: 22, max: 29.99 },
          great: { min: 18, max: 21.99 },
          elite: { min: 0, max: 17.99 },
        },
        '40-59': {
          poor: { min: 38, max: 99 },
          cautious: { min: 33, max: 37.99 },
          normal: { min: 25, max: 32.99 },
          great: { min: 20, max: 24.99 },
          elite: { min: 0, max: 19.99 },
        },
        '60+': {
          poor: { min: 40, max: 99 },
          cautious: { min: 35, max: 39.99 },
          normal: { min: 28, max: 34.99 },
          great: { min: 23, max: 27.99 },
          elite: { min: 0, max: 22.99 },
        },
      },
    },

    waist_to_hip: {
      unit: 'ratio',
      male: {
        poor: { min: 1.00, max: 2.00 },
        cautious: { min: 0.95, max: 0.99 },
        normal: { min: 0.90, max: 0.94 },
        great: { min: 0.85, max: 0.89 },
        elite: { min: 0.00, max: 0.84 },
      },
      female: {
        poor: { min: 0.90, max: 2.00 },
        cautious: { min: 0.86, max: 0.89 },
        normal: { min: 0.80, max: 0.85 },
        great: { min: 0.75, max: 0.79 },
        elite: { min: 0.00, max: 0.74 },
      },
    },
  },

  fitness: {
    vo2max: {
      unit: 'ml/kg/min',
      note: 'Simple 5-tier buckets; adjust to your preferred reference set.',
      male: {
        '18-25': { poor: { min: 0, max: 41.9 }, cautious: { min: 42, max: 46.9 }, normal: { min: 47, max: 52.9 }, great: { min: 53, max: 57.9 }, elite: { min: 58, max: 99 } },
        '26-35': { poor: { min: 0, max: 39.9 }, cautious: { min: 40, max: 44.9 }, normal: { min: 45, max: 50.9 }, great: { min: 51, max: 55.9 }, elite: { min: 56, max: 99 } },
        '36-45': { poor: { min: 0, max: 36.9 }, cautious: { min: 37, max: 41.9 }, normal: { min: 42, max: 47.9 }, great: { min: 48, max: 52.9 }, elite: { min: 53, max: 99 } },
        '46-55': { poor: { min: 0, max: 32.9 }, cautious: { min: 33, max: 36.9 }, normal: { min: 37, max: 41.9 }, great: { min: 42, max: 45.9 }, elite: { min: 46, max: 99 } },
        '56-65': { poor: { min: 0, max: 29.9 }, cautious: { min: 30, max: 32.9 }, normal: { min: 33, max: 36.9 }, great: { min: 37, max: 40.9 }, elite: { min: 41, max: 99 } },
        '66+': { poor: { min: 0, max: 25.9 }, cautious: { min: 26, max: 28.9 }, normal: { min: 29, max: 31.9 }, great: { min: 32, max: 34.9 }, elite: { min: 35, max: 99 } },
      },
      female: {
        '18-25': { poor: { min: 0, max: 36.9 }, cautious: { min: 37, max: 41.9 }, normal: { min: 42, max: 46.9 }, great: { min: 47, max: 51.9 }, elite: { min: 52, max: 99 } },
        '26-35': { poor: { min: 0, max: 34.9 }, cautious: { min: 35, max: 38.9 }, normal: { min: 39, max: 43.9 }, great: { min: 44, max: 48.9 }, elite: { min: 49, max: 99 } },
        '36-45': { poor: { min: 0, max: 31.9 }, cautious: { min: 32, max: 35.9 }, normal: { min: 36, max: 40.9 }, great: { min: 41, max: 45.9 }, elite: { min: 46, max: 99 } },
        '46-55': { poor: { min: 0, max: 27.9 }, cautious: { min: 28, max: 31.9 }, normal: { min: 32, max: 35.9 }, great: { min: 36, max: 39.9 }, elite: { min: 40, max: 99 } },
        '56-65': { poor: { min: 0, max: 24.9 }, cautious: { min: 25, max: 27.9 }, normal: { min: 28, max: 31.9 }, great: { min: 32, max: 34.9 }, elite: { min: 35, max: 99 } },
        '66+': { poor: { min: 0, max: 21.9 }, cautious: { min: 22, max: 24.9 }, normal: { min: 25, max: 27.9 }, great: { min: 28, max: 30.9 }, elite: { min: 31, max: 99 } },
      },
    },

    resting_hr: {
      unit: 'bpm',
      note: 'Lower is generally better; interpret with symptoms/med history.',
      poor: { min: 90, max: 220 },
      cautious: { min: 80, max: 89 },
      normal: { min: 60, max: 79 },
      great: { min: 50, max: 59 },
      elite: { min: 30, max: 49 },
    },

    blood_pressure_systolic: {
      unit: 'mmHg',
      note: 'General adult categories; verify with clinical guidelines.',
      poor: { min: 140, max: 300 },
      cautious: { min: 130, max: 139 },
      normal: { min: 110, max: 129 },
      great: { min: 100, max: 109 },
      elite: { min: 0, max: 99 },
    },
  },

  strength: {
    grip_strength_left: {
      unit: 'kg',
      note: 'Handgrip dynamometry — strong predictor of all-cause mortality.',
      male: {
        poor: { min: 0, max: 29.9 },
        cautious: { min: 30, max: 35.9 },
        normal: { min: 36, max: 44.9 },
        great: { min: 45, max: 55.9 },
        elite: { min: 56, max: 999 },
      },
      female: {
        poor: { min: 0, max: 17.9 },
        cautious: { min: 18, max: 23.9 },
        normal: { min: 24, max: 31.9 },
        great: { min: 32, max: 38.9 },
        elite: { min: 39, max: 999 },
      },
    },
    grip_strength_right: {
      unit: 'kg',
      note: 'Handgrip dynamometry — strong predictor of all-cause mortality.',
      male: {
        poor: { min: 0, max: 29.9 },
        cautious: { min: 30, max: 35.9 },
        normal: { min: 36, max: 44.9 },
        great: { min: 45, max: 55.9 },
        elite: { min: 56, max: 999 },
      },
      female: {
        poor: { min: 0, max: 17.9 },
        cautious: { min: 18, max: 23.9 },
        normal: { min: 24, max: 31.9 },
        great: { min: 32, max: 38.9 },
        elite: { min: 39, max: 999 },
      },
    },
    cmj_left: {
      unit: 'cm',
      note: 'Countermovement jump height — lower-body power indicator.',
      male: {
        poor: { min: 0, max: 19.9 },
        cautious: { min: 20, max: 24.9 },
        normal: { min: 25, max: 34.9 },
        great: { min: 35, max: 44.9 },
        elite: { min: 45, max: 999 },
      },
      female: {
        poor: { min: 0, max: 11.9 },
        cautious: { min: 12, max: 16.9 },
        normal: { min: 17, max: 24.9 },
        great: { min: 25, max: 32.9 },
        elite: { min: 33, max: 999 },
      },
    },
    cmj_right: {
      unit: 'cm',
      note: 'Countermovement jump height — lower-body power indicator.',
      male: {
        poor: { min: 0, max: 19.9 },
        cautious: { min: 20, max: 24.9 },
        normal: { min: 25, max: 34.9 },
        great: { min: 35, max: 44.9 },
        elite: { min: 45, max: 999 },
      },
      female: {
        poor: { min: 0, max: 11.9 },
        cautious: { min: 12, max: 16.9 },
        normal: { min: 17, max: 24.9 },
        great: { min: 25, max: 32.9 },
        elite: { min: 33, max: 999 },
      },
    },
    imtp_max_force: {
      unit: 'kg',
      note: 'Isometric mid-thigh pull — peak force production.',
      male: {
        poor: { min: 0, max: 79.9 },
        cautious: { min: 80, max: 119.9 },
        normal: { min: 120, max: 179.9 },
        great: { min: 180, max: 239.9 },
        elite: { min: 240, max: 9999 },
      },
      female: {
        poor: { min: 0, max: 39.9 },
        cautious: { min: 40, max: 69.9 },
        normal: { min: 70, max: 109.9 },
        great: { min: 110, max: 149.9 },
        elite: { min: 150, max: 9999 },
      },
    },
    single_leg_hop_left: {
      unit: 'cm',
      note: 'Single leg hop — reactive strength and symmetry.',
      male: {
        poor: { min: 0, max: 14.9 },
        cautious: { min: 15, max: 19.9 },
        normal: { min: 20, max: 29.9 },
        great: { min: 30, max: 39.9 },
        elite: { min: 40, max: 999 },
      },
      female: {
        poor: { min: 0, max: 9.9 },
        cautious: { min: 10, max: 14.9 },
        normal: { min: 15, max: 22.9 },
        great: { min: 23, max: 30.9 },
        elite: { min: 31, max: 999 },
      },
    },
    single_leg_hop_right: {
      unit: 'cm',
      note: 'Single leg hop — reactive strength and symmetry.',
      male: {
        poor: { min: 0, max: 14.9 },
        cautious: { min: 15, max: 19.9 },
        normal: { min: 20, max: 29.9 },
        great: { min: 30, max: 39.9 },
        elite: { min: 40, max: 999 },
      },
      female: {
        poor: { min: 0, max: 9.9 },
        cautious: { min: 10, max: 14.9 },
        normal: { min: 15, max: 22.9 },
        great: { min: 23, max: 30.9 },
        elite: { min: 31, max: 999 },
      },
    },
    single_leg_balance_left: {
      unit: 'mm²',
      note: 'Balance area — lower is better (less sway = better stability).',
      poor: { min: 800, max: 99999 },
      cautious: { min: 500, max: 799 },
      normal: { min: 300, max: 499 },
      great: { min: 150, max: 299 },
      elite: { min: 0, max: 149 },
    },
    single_leg_balance_right: {
      unit: 'mm²',
      note: 'Balance area — lower is better (less sway = better stability).',
      poor: { min: 800, max: 99999 },
      cautious: { min: 500, max: 799 },
      normal: { min: 300, max: 499 },
      great: { min: 150, max: 299 },
      elite: { min: 0, max: 149 },
    },
    shoulder_iso_y_left: {
      unit: 'kg',
      note: 'Shoulder isometric Y-raise — rotator cuff and scapular stability.',
      male: {
        poor: { min: 0, max: 2.9 },
        cautious: { min: 3, max: 4.9 },
        normal: { min: 5, max: 7.9 },
        great: { min: 8, max: 10.9 },
        elite: { min: 11, max: 999 },
      },
      female: {
        poor: { min: 0, max: 1.4 },
        cautious: { min: 1.5, max: 2.9 },
        normal: { min: 3, max: 4.9 },
        great: { min: 5, max: 6.9 },
        elite: { min: 7, max: 999 },
      },
    },
    shoulder_iso_y_right: {
      unit: 'kg',
      note: 'Shoulder isometric Y-raise — rotator cuff and scapular stability.',
      male: {
        poor: { min: 0, max: 2.9 },
        cautious: { min: 3, max: 4.9 },
        normal: { min: 5, max: 7.9 },
        great: { min: 8, max: 10.9 },
        elite: { min: 11, max: 999 },
      },
      female: {
        poor: { min: 0, max: 1.4 },
        cautious: { min: 1.5, max: 2.9 },
        normal: { min: 3, max: 4.9 },
        great: { min: 5, max: 6.9 },
        elite: { min: 7, max: 999 },
      },
    },
    pushups_max: {
      unit: 'reps',
      note: 'Push-up max test — upper body muscular endurance.',
      male: {
        '20-39': {
          poor: { min: 0, max: 14 },
          cautious: { min: 15, max: 19 },
          normal: { min: 20, max: 29 },
          great: { min: 30, max: 39 },
          elite: { min: 40, max: 999 },
        },
        '40-59': {
          poor: { min: 0, max: 9 },
          cautious: { min: 10, max: 14 },
          normal: { min: 15, max: 24 },
          great: { min: 25, max: 34 },
          elite: { min: 35, max: 999 },
        },
        '60+': {
          poor: { min: 0, max: 4 },
          cautious: { min: 5, max: 9 },
          normal: { min: 10, max: 19 },
          great: { min: 20, max: 29 },
          elite: { min: 30, max: 999 },
        },
      },
      female: {
        '20-39': {
          poor: { min: 0, max: 4 },
          cautious: { min: 5, max: 9 },
          normal: { min: 10, max: 19 },
          great: { min: 20, max: 29 },
          elite: { min: 30, max: 999 },
        },
        '40-59': {
          poor: { min: 0, max: 2 },
          cautious: { min: 3, max: 6 },
          normal: { min: 7, max: 14 },
          great: { min: 15, max: 24 },
          elite: { min: 25, max: 999 },
        },
        '60+': {
          poor: { min: 0, max: 1 },
          cautious: { min: 2, max: 4 },
          normal: { min: 5, max: 11 },
          great: { min: 12, max: 19 },
          elite: { min: 20, max: 999 },
        },
      },
    },
    dead_man_hang: {
      unit: 'sec',
      note: 'Dead man hang — grip endurance and shoulder health.',
      male: {
        poor: { min: 0, max: 14.9 },
        cautious: { min: 15, max: 29.9 },
        normal: { min: 30, max: 59.9 },
        great: { min: 60, max: 89.9 },
        elite: { min: 90, max: 9999 },
      },
      female: {
        poor: { min: 0, max: 9.9 },
        cautious: { min: 10, max: 19.9 },
        normal: { min: 20, max: 39.9 },
        great: { min: 40, max: 59.9 },
        elite: { min: 60, max: 9999 },
      },
    },
    farmers_carry_distance: {
      unit: 'm',
      note: 'Farmers carry at bodyweight — loaded carry endurance.',
      poor: { min: 0, max: 19.9 },
      cautious: { min: 20, max: 39.9 },
      normal: { min: 40, max: 59.9 },
      great: { min: 60, max: 79.9 },
      elite: { min: 80, max: 9999 },
    },
  },

  mobility: {
    hip_mobility_left: {
      unit: 'cm',
      note: 'Higher is better (example scale). Replace with your test\'s real scoring.',
      poor: { min: 0, max: 4.9 },
      cautious: { min: 5, max: 7.9 },
      normal: { min: 8, max: 10.9 },
      great: { min: 11, max: 13.9 },
      elite: { min: 14, max: 99 },
    },
    hip_mobility_right: {
      unit: 'cm',
      note: 'Higher is better (example scale). Replace with your test\'s real scoring.',
      poor: { min: 0, max: 4.9 },
      cautious: { min: 5, max: 7.9 },
      normal: { min: 8, max: 10.9 },
      great: { min: 11, max: 13.9 },
      elite: { min: 14, max: 99 },
    },
  },
};
