export const fieldMappings: Record<string, string> = {
  // Body Composition (Evolt 360)
  'body fat': 'bodyFatPercentage',
  'bodyfat': 'bodyFatPercentage',
  'body_fat': 'bodyFatPercentage',
  'body fat percentage': 'bodyFatPercentage',
  'total body fat percentage': 'bodyFatPercentage',
  'total body fat %': 'bodyFatPercentage',
  'total body fat': 'bodyFatPercentage',
  'lean mass': 'leanMass',
  'lean body mass': 'leanMass',
  'skeletal muscle': 'skeletalMuscleMass',
  'skeletal muscle mass': 'skeletalMuscleMass',
  'muscle mass': 'skeletalMuscleMass',
  'fat mass': 'fatMass',
  'body fat mass': 'fatMass',
  'visceral': 'visceralFatRating',
  'visceral fat level': 'visceralFatRating',
  'visceral fat rating': 'visceralFatRating',
  'waist hip': 'waistToHipRatio',
  'waist to hip ratio': 'waistToHipRatio',
  'waist hip ratio': 'waistToHipRatio',
  'whr': 'waistToHipRatio',
  'bmr': 'bmr',
  'basal metabolic': 'bmr',
  'basal metabolic rate': 'bmr',
  'bwi': 'bwi',
  'bwi score': 'bwi',
  'bio wellness': 'bwi',
  'bio wellness index': 'bwi',

  // Hormones
  'free testosterone': 'freeTestosterone',
  'free test': 'freeTestosterone',
  'total testosterone': 'totalTestosterone',
  'testosterone total': 'totalTestosterone',
  'oestradiol': 'oestradiol',
  'estradiol': 'oestradiol',
  'e2': 'oestradiol',
  'shbg': 'shbg',
  'sex hormone binding': 'shbg',
  'fsh': 'fsh',
  'follicle stimulating': 'fsh',
  'lh': 'lh',
  'luteinizing': 'lh',
  'prolactin': 'prolactin',
  'progesterone': 'progesterone',
  'cortisol': 'cortisol',
  'dheas': 'dheas',
  'dhea-s': 'dheas',
  'igf-1': 'igf1',
  'igf1': 'igf1',
  'igf 1': 'igf1',

  // Lipids
  'total cholesterol': 'cholesterolTotal',
  'cholesterol total': 'cholesterolTotal',
  'ldl': 'ldl',
  'ldl cholesterol': 'ldl',
  'hdl': 'hdl',
  'hdl cholesterol': 'hdl',
  'triglycerides': 'triglycerides',
  'triglyceride': 'triglycerides',

  // Metabolic
  'glucose': 'glucose',
  'blood glucose': 'glucose',
  'fasting glucose': 'glucose',
  'hba1c': 'hba1c',
  'hgba1c': 'hba1c',
  'a1c': 'hba1c',
  'insulin': 'insulin',
  'fasting insulin': 'insulin',

  // Thyroid
  'tsh': 'tsh',
  'thyroid stimulating': 'tsh',
  'ft3': 'ft3',
  'free t3': 'ft3',
  'free triiodothyronine': 'ft3',
  'ft4': 'ft4',
  'free t4': 'ft4',
  'free thyroxine': 'ft4',
  'thyroglobulin': 'tgab',
  'tgab': 'tgab',
  'thyroperoxidase': 'tpo',
  'tpo': 'tpo',
  'anti-tpo': 'tpo',

  // Iron Studies
  'serum iron': 'serumIron',
  'iron': 'serumIron',
  'tibc': 'tibc',
  'iron binding': 'tibc',
  'transferrin saturation': 'transferrinSat',
  'transferrin': 'transferrinSat',
  'ferritin': 'ferritin',

  // Vitamins
  'vitamin d': 'vitaminD',
  '25-oh vitamin d': 'vitaminD',
  'vit d': 'vitaminD',

  // Full Blood Count
  'hemoglobin': 'hemoglobin',
  'haemoglobin': 'hemoglobin',
  'hgb': 'hemoglobin',
  'red blood cell': 'rbc',
  'rbc': 'rbc',
  'hematocrit': 'hematocrit',
  'haematocrit': 'hematocrit',
  'hct': 'hematocrit',
  'white blood cell': 'wbc',
  'wbc': 'wbc',
  'platelet': 'platelet',
  'plt': 'platelet',
  'mcv': 'mcv',
  'mean corpuscular volume': 'mcv',
  'mch': 'mch',
  'mean corpuscular hemoglobin': 'mch',

  // Kidney Function & Electrolytes
  'creatinine': 'creatinine',
  'egfr': 'egfr',
  'gfr': 'egfr',
  'glomerular filtration': 'egfr',
  'bun': 'bun',
  'blood urea nitrogen': 'bun',
  'urea': 'bun',
  'sodium': 'sodium',
  'na': 'sodium',
  'potassium': 'potassium',
  'k': 'potassium',
  'chloride': 'chloride',
  'cl': 'chloride',
  'bicarbonate': 'bicarbonate',
  'hco3': 'bicarbonate',

  // Liver Function Tests
  'alt': 'alt',
  'alanine aminotransferase': 'alt',
  'sgpt': 'alt',
  'ast': 'ast',
  'aspartate aminotransferase': 'ast',
  'sgot': 'ast',
  'alp': 'alp',
  'alkaline phosphatase': 'alp',
  'ggt': 'ggt',
  'gamma-glutamyl': 'ggt',
  'gamma glutamyl': 'ggt',
  'bilirubin': 'bilirubin',
  'total bilirubin': 'bilirubin',
  'albumin': 'albumin',
  'total protein': 'totalProtein',

  // Advanced Lipids
  'apob': 'apoB',
  'apo b': 'apoB',
  'apolipoprotein b': 'apoB',
  'lp(a)': 'lpa',
  'lpa': 'lpa',
  'lipoprotein(a)': 'lpa',
  'lipoprotein a': 'lpa',

  // Inflammation & Other
  'hs-crp': 'hsCRP',
  'hscrp': 'hsCRP',
  'c-reactive protein': 'hsCRP',
  'crp': 'hsCRP',
  'homocysteine': 'homocysteine',
  'creatine kinase': 'ck',
  'ck': 'ck',
  'cpk': 'ck',
  'uric acid': 'uricAcid',
  'urate': 'uricAcid',

  // Additional Vitamins & Minerals
  'vitamin b12': 'vitaminB12',
  'b12': 'vitaminB12',
  'cobalamin': 'vitaminB12',
  'folate': 'folate',
  'folic acid': 'folate',
  'vitamin b9': 'folate',
  'magnesium': 'magnesium',
  'mg': 'magnesium',
  'zinc': 'zinc',
  'zn': 'zinc',

  // Heavy Metals
  'lead': 'lead',
  'pb': 'lead',
  'mercury': 'mercury',
  'hg': 'mercury',
  'arsenic': 'arsenic',
  'as': 'arsenic',
  'cadmium': 'cadmium',
  'cd': 'cadmium',
};
